--------------------------------------------------------
--  File created - Monday-December-24-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADMIN_EDU_YEAR
--------------------------------------------------------

  CREATE TABLE "TANSIQ"."ADMIN_EDU_YEAR" 
   (	"USER_ID" NUMBER, 
	"EDU_LEVEL" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE( MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEP_PREREQ
--------------------------------------------------------

  CREATE TABLE "TANSIQ"."DEP_PREREQ" 
   (	"DEP_ID" NUMBER, 
	"PREREQ_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE( MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEPARTMENT
--------------------------------------------------------

  CREATE TABLE "TANSIQ"."DEPARTMENT" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(50 BYTE), 
	"MIN_CAP" NUMBER, 
	"MAX_CAP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EDU_LEVEL
--------------------------------------------------------

  CREATE TABLE "TANSIQ"."EDU_LEVEL" 
   (	"ID" NUMBER, 
	"DEPARTMENT" VARCHAR2(50 BYTE), 
	"FACULTY" VARCHAR2(50 BYTE), 
	"YEAR" NUMBER, 
	"DEPARTMENT_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EDU_LEVEL_DEPARTMENT
--------------------------------------------------------

  CREATE TABLE "TANSIQ"."EDU_LEVEL_DEPARTMENT" 
   (	"EDU_LEVEL_ID" NUMBER, 
	"DEPARTMENT_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MESSAGES
--------------------------------------------------------

  CREATE TABLE "TANSIQ"."MESSAGES" 
   (	"FROM_USER_ID" NUMBER, 
	"REPORT" VARCHAR2(1000 BYTE), 
	"TO_USER_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE( MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PREREQUISITE
--------------------------------------------------------

  CREATE TABLE "TANSIQ"."PREREQUISITE" 
   (	"SUBJECT" NUMBER, 
	"ID" NUMBER, 
	"MIN_MARK_SUBJECT" NUMBER, 
	"CURRENT_EDU_LEVEL_ID" NUMBER, 
	"MIN_MARK_DEP" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE( MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROLES
--------------------------------------------------------

  CREATE TABLE "TANSIQ"."ROLES" 
   (	"USER_ID" NUMBER, 
	"ROLE_ID" NUMBER DEFAULT 0, 
	"ROLES" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "TANSIQ"."ROLES"."ROLES" IS '0 IS STUDENT';
--------------------------------------------------------
--  DDL for Table STUDENT
--------------------------------------------------------

  CREATE TABLE "TANSIQ"."STUDENT" 
   (	"USER_ID" NUMBER, 
	"EDU_LEVEL" NUMBER, 
	"TOTAL_MARK" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STUDENT_SUBJECT
--------------------------------------------------------

  CREATE TABLE "TANSIQ"."STUDENT_SUBJECT" 
   (	"STUDENT" NUMBER, 
	"SUBJECT" NUMBER, 
	"MARK" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE( MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STUDENTS_REQUESTS
--------------------------------------------------------

  CREATE TABLE "TANSIQ"."STUDENTS_REQUESTS" 
   (	"DEP_ID" NUMBER, 
	"STUDENT_ID" NUMBER, 
	"ORDER" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE( MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SUBJECT
--------------------------------------------------------

  CREATE TABLE "TANSIQ"."SUBJECT" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(30 BYTE), 
	"EDU_LEVEL_ID" NUMBER(*,0), 
	"EDU_LEVEL_ID1" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE( MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TIMELINE
--------------------------------------------------------

  CREATE TABLE "TANSIQ"."TIMELINE" 
   (	"EDU_LEVEL_ID" NUMBER, 
	"START_DATE" DATE, 
	"END_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE( MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USER_WEBSITE
--------------------------------------------------------

  CREATE TABLE "TANSIQ"."USER_WEBSITE" 
   (	"ROLE" NUMBER, 
	"WEBSITE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "TANSIQ"."USERS" 
   (	"ID" NUMBER, 
	"USER_NAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"ROLE" NUMBER DEFAULT 0, 
	"FIRST_NAME" VARCHAR2(15 BYTE), 
	"MIDDLE_NAME" VARCHAR2(15 BYTE), 
	"LAST_NAME" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DEPARTMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TANSIQ"."DEPARTMENT_PK" ON "TANSIQ"."DEPARTMENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EDU_LEVEL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TANSIQ"."EDU_LEVEL_PK" ON "TANSIQ"."EDU_LEVEL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PREREQUISITE_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "TANSIQ"."PREREQUISITE_PK1" ON "TANSIQ"."PREREQUISITE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  STORAGE( MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ROLES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TANSIQ"."ROLES_PK" ON "TANSIQ"."ROLES" ("ROLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STUDENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TANSIQ"."STUDENT_PK" ON "TANSIQ"."STUDENT" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SUBJECT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TANSIQ"."SUBJECT_PK" ON "TANSIQ"."SUBJECT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  STORAGE( MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TANSIQ"."TABLE1_PK" ON "TANSIQ"."USERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TABLE1_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "TANSIQ"."TABLE1_UK1" ON "TANSIQ"."USERS" ("USER_NAME", "EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger ROLES_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TANSIQ"."ROLES_TRG" 
BEFORE INSERT ON ROLES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ROLE_ID IS NULL THEN
      SELECT ROLES_SEQ.NEXTVAL INTO :NEW.ROLE_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TANSIQ"."ROLES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SUBJECT_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TANSIQ"."SUBJECT_TRG" 
BEFORE INSERT ON SUBJECT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT SUBJECT_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TANSIQ"."SUBJECT_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table ADMIN_EDU_YEAR
--------------------------------------------------------

  ALTER TABLE "TANSIQ"."ADMIN_EDU_YEAR" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TANSIQ"."ADMIN_EDU_YEAR" MODIFY ("EDU_LEVEL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEP_PREREQ
--------------------------------------------------------

  ALTER TABLE "TANSIQ"."DEP_PREREQ" MODIFY ("DEP_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TANSIQ"."DEP_PREREQ" MODIFY ("PREREQ_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEPARTMENT
--------------------------------------------------------

  ALTER TABLE "TANSIQ"."DEPARTMENT" ADD CONSTRAINT "DEPARTMENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "TANSIQ"."DEPARTMENT" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "TANSIQ"."DEPARTMENT" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "TANSIQ"."DEPARTMENT" MODIFY ("MIN_CAP" NOT NULL ENABLE);
 
  ALTER TABLE "TANSIQ"."DEPARTMENT" MODIFY ("MAX_CAP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EDU_LEVEL
--------------------------------------------------------

  ALTER TABLE "TANSIQ"."EDU_LEVEL" ADD CONSTRAINT "EDU_LEVEL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "TANSIQ"."EDU_LEVEL" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "TANSIQ"."EDU_LEVEL" MODIFY ("FACULTY" NOT NULL ENABLE);
 
  ALTER TABLE "TANSIQ"."EDU_LEVEL" MODIFY ("YEAR" NOT NULL ENABLE);
 
  ALTER TABLE "TANSIQ"."EDU_LEVEL" MODIFY ("DEPARTMENT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EDU_LEVEL_DEPARTMENT
--------------------------------------------------------

  ALTER TABLE "TANSIQ"."EDU_LEVEL_DEPARTMENT" MODIFY ("EDU_LEVEL_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TANSIQ"."EDU_LEVEL_DEPARTMENT" MODIFY ("DEPARTMENT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MESSAGES
--------------------------------------------------------

  ALTER TABLE "TANSIQ"."MESSAGES" MODIFY ("FROM_USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TANSIQ"."MESSAGES" MODIFY ("REPORT" NOT NULL ENABLE);
 
  ALTER TABLE "TANSIQ"."MESSAGES" MODIFY ("TO_USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PREREQUISITE
--------------------------------------------------------

  ALTER TABLE "TANSIQ"."PREREQUISITE" ADD CONSTRAINT "PREREQUISITE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  STORAGE( MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "TANSIQ"."PREREQUISITE" MODIFY ("SUBJECT" NOT NULL ENABLE);
 
  ALTER TABLE "TANSIQ"."PREREQUISITE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "TANSIQ"."PREREQUISITE" MODIFY ("MIN_MARK_SUBJECT" NOT NULL ENABLE);
 
  ALTER TABLE "TANSIQ"."PREREQUISITE" MODIFY ("CURRENT_EDU_LEVEL_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TANSIQ"."PREREQUISITE" MODIFY ("MIN_MARK_DEP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROLES
--------------------------------------------------------

  ALTER TABLE "TANSIQ"."ROLES" ADD CONSTRAINT "ROLES_PK" PRIMARY KEY ("ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "TANSIQ"."ROLES" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TANSIQ"."ROLES" MODIFY ("ROLE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TANSIQ"."ROLES" MODIFY ("ROLES" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STUDENT
--------------------------------------------------------

  ALTER TABLE "TANSIQ"."STUDENT" ADD CONSTRAINT "STUDENT_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "TANSIQ"."STUDENT" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TANSIQ"."STUDENT" MODIFY ("EDU_LEVEL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STUDENT_SUBJECT
--------------------------------------------------------

  ALTER TABLE "TANSIQ"."STUDENT_SUBJECT" MODIFY ("STUDENT" NOT NULL ENABLE);
 
  ALTER TABLE "TANSIQ"."STUDENT_SUBJECT" MODIFY ("SUBJECT" NOT NULL ENABLE);
 
  ALTER TABLE "TANSIQ"."STUDENT_SUBJECT" MODIFY ("MARK" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STUDENTS_REQUESTS
--------------------------------------------------------

  ALTER TABLE "TANSIQ"."STUDENTS_REQUESTS" MODIFY ("DEP_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TANSIQ"."STUDENTS_REQUESTS" MODIFY ("STUDENT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TANSIQ"."STUDENTS_REQUESTS" MODIFY ("ORDER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SUBJECT
--------------------------------------------------------

  ALTER TABLE "TANSIQ"."SUBJECT" ADD CONSTRAINT "SUBJECT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  STORAGE( MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "TANSIQ"."SUBJECT" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "TANSIQ"."SUBJECT" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "TANSIQ"."SUBJECT" MODIFY ("EDU_LEVEL_ID1" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIMELINE
--------------------------------------------------------

  ALTER TABLE "TANSIQ"."TIMELINE" MODIFY ("EDU_LEVEL_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TANSIQ"."TIMELINE" MODIFY ("START_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "TANSIQ"."TIMELINE" MODIFY ("END_DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USER_WEBSITE
--------------------------------------------------------

  ALTER TABLE "TANSIQ"."USER_WEBSITE" MODIFY ("ROLE" NOT NULL ENABLE);
 
  ALTER TABLE "TANSIQ"."USER_WEBSITE" MODIFY ("WEBSITE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "TANSIQ"."USERS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "TANSIQ"."USERS" MODIFY ("USER_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "TANSIQ"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
 
  ALTER TABLE "TANSIQ"."USERS" MODIFY ("EMAIL" NOT NULL ENABLE);
 
  ALTER TABLE "TANSIQ"."USERS" MODIFY ("ROLE" NOT NULL ENABLE);
 
  ALTER TABLE "TANSIQ"."USERS" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "TANSIQ"."USERS" MODIFY ("LAST_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "TANSIQ"."USERS" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "TANSIQ"."USERS" ADD CONSTRAINT "TABLE1_UK1" UNIQUE ("USER_NAME", "EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
